/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abcd: typeof import('./src/components/abcd.md')['default']
    IconCarbonDirectionStraightRight: typeof import('~icons/carbon/direction-straight-right')['default']
    IconCustomArrowRightCircle: typeof import('~icons/custom/arrow-right-circle')['default']
    IconCustomClose: typeof import('~icons/custom/close')['default']
    IconCustomDirectionRight: typeof import('~icons/custom/direction-right')['default']
    IconCustomMenu: typeof import('~icons/custom/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/models/users/UserList.vue')['default']
    ZCard: typeof import('./src/components/ZCard.vue')['default']
    ZContainer: typeof import('./src/components/ZContainer.vue')['default']
    ZImage: typeof import('./src/components/ZImage.vue')['default']
    ZMenu: typeof import('./src/components/ZMenu.vue')['default']
    ZSwiper: typeof import('./src/components/ZSwiper.vue')['default']
    ZSwiperMk: typeof import('./src/components/ZSwiperMk.vue')['default']
    ZSwiperWidthContent: typeof import('./src/components/ZSwiperWidthContent.vue')['default']
  }
}
