/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    IconCustomArrowRightCircle: typeof import('~icons/custom/arrow-right-circle')['default']
    IconCustomClose: typeof import('~icons/custom/close')['default']
    IconCustomMenu: typeof import('~icons/custom/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/models/users/UserList.vue')['default']
    ZCard: typeof import('./src/components/ZCard.vue')['default']
    ZContainer: typeof import('./src/components/ZContainer.vue')['default']
    ZImage: typeof import('./src/components/ZImage.vue')['default']
    ZMenu: typeof import('./src/components/ZMenu.vue')['default']
    ZSwiper: typeof import('./src/components/ZSwiper.vue')['default']
  }
}
